### ISSUE TITLE
Release pipeline and first release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-shoal#129]
We need to create a release CI/CD pipeline for this project and release the first version from Eclipse. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by jayasheelankumar** [comment]
Release job is done and the dryrun is complete
